/** One operator role owns its DAG label and full detail name. Layout aliases preserve accepted geometry. */
export interface OperatorPresentation { layoutAlias?: string; shortName?: string; title?: string; explanation?: string }
export const OPERATOR_CATALOG: Readonly<Record<string, OperatorPresentation>> = {
  "patch-project": {"layoutAlias": "Patch", "shortName": "patch", "title": "Patch projection"},
  "attention-norm": {"layoutAlias": "Norm", "shortName": "归一化"},
  "query-projection": {"layoutAlias": "Q", "shortName": "Q", "title": "Q projection"},
  "key-projection": {"layoutAlias": "K", "shortName": "K", "title": "K projection"},
  "value-projection": {"layoutAlias": "V", "shortName": "V", "title": "V projection"},
  "attention": {"layoutAlias": "Attn", "shortName": "Attention"},
  "output-projection": {"layoutAlias": "O", "shortName": "O", "title": "Attention output projection"},
  "attention-residual": {"layoutAlias": "Add", "shortName": "相加", "title": "Attention residual addition"},
  "mlp-norm": {"layoutAlias": "MLP norm", "shortName": "MLP 归一化"},
  "mlp-up-projection": {"layoutAlias": "Up", "shortName": "Up", "title": "MLP Up projection"},
  "mlp-gelu": {"layoutAlias": "GELU", "shortName": "GELU"},
  "mlp-down-projection": {"layoutAlias": "Down", "shortName": "Down", "title": "MLP Down projection"},
  "mlp-residual": {"layoutAlias": "Add", "shortName": "相加", "title": "MLP residual addition"},
  "normalize": {"layoutAlias": "Final norm", "shortName": "末层归一化"},
  "project": {"layoutAlias": "Project", "shortName": "Proj", "title": "Vision projection"},
  "flatten-views": {"layoutAlias": "reshape", "shortName": "reshape"},
  "embed-prompt": {"layoutAlias": "Token embed", "shortName": "Embedding", "title": "Prompt embedding"},
  "build-prefix": {"layoutAlias": "concat", "shortName": "concat"},
  "query-rope": {"layoutAlias": "Q RoPE", "shortName": "Q RoPE", "title": "Q RoPE"},
  "key-rope": {"layoutAlias": "K RoPE", "shortName": "K RoPE", "title": "K RoPE"},
  "cache-output": {"layoutAlias": "Prefix KV", "shortName": "前缀 KV"},
  "gate-projection": {"layoutAlias": "Gate", "shortName": "Gate", "title": "MLP Gate projection"},
  "up-projection": {"layoutAlias": "Up", "shortName": "Up", "title": "MLP Up projection"},
  "gate-gelu": {"layoutAlias": "GELU", "shortName": "GELU"},
  "gate-product": {"layoutAlias": "Mul", "shortName": "相乘", "title": "MLP Gate multiplication"},
  "down-projection": {"layoutAlias": "Down", "shortName": "Down", "title": "MLP Down projection"},
  "state-projection": {"layoutAlias": "State token", "shortName": "state token", "title": "State projection"},
  "action-projection": {"layoutAlias": "Action", "shortName": "动作", "title": "Action projection"},
  "time-embedding": {"layoutAlias": "Sin/Cos", "shortName": "Sin/Cos", "title": "Sinusoidal time embedding"},
  "action-time-concat": {"layoutAlias": "action + time", "shortName": "动作 + 时间", "title": "Action/time concat"},
  "time-mlp-in": {"layoutAlias": "MLP in", "shortName": "输入 Proj"},
  "time-mlp-silu": {"layoutAlias": "SiLU", "shortName": "SiLU"},
  "time-mlp-out": {"layoutAlias": "MLP out", "shortName": "输出 Proj"},
  "suffix-concat": {"layoutAlias": "concat", "shortName": "concat", "title": "State/action concat"},
  "extract-prefix-key": {"layoutAlias": "Prefix K", "shortName": "前缀 K", "title": "Prefix K selection"},
  "extract-prefix-value": {"layoutAlias": "Prefix V", "shortName": "前缀 V", "title": "Prefix V selection"},
  "key-concat": {"layoutAlias": "K view", "shortName": "K 视图", "title": "Prefix/suffix K concat"},
  "value-concat": {"layoutAlias": "V view", "shortName": "V 视图", "title": "Prefix/suffix V concat"},
  "final-norm": {"layoutAlias": "Final RMSNorm", "shortName": "末层 RMSNorm"},
  "select-action-rows": {"layoutAlias": "Row slice", "shortName": "行选择", "title": "Action token selection"},
  "velocity-projection": {"layoutAlias": "Velocity", "shortName": "速度 Proj", "title": "Velocity projection"},
  "euler-update": {"layoutAlias": "Euler", "shortName": "欧拉更新"},
  "gate-silu": {"layoutAlias": "SiLU", "shortName": "SiLU"},
  "image-language-concat": {"layoutAlias": "image + text", "shortName": "图像 + 文本", "title": "Vision/prompt concat"},
  "key-cache-output": {"layoutAlias": "K cache", "shortName": "K 缓存", "title": "K cache view"},
  "value-cache-output": {"layoutAlias": "V cache", "shortName": "V 缓存", "title": "V cache view"},
  "broadcast-time": {"layoutAlias": "broadcast", "shortName": "广播"},
  "time-silu-in": {"layoutAlias": "SiLU", "shortName": "SiLU"},
  "time-silu-out": {"layoutAlias": "SiLU", "shortName": "SiLU"},
  "flatten-prefix-key": {"layoutAlias": "flatten K", "shortName": "展平 K"},
  "flatten-prefix-value": {"layoutAlias": "flatten V", "shortName": "展平 V"},
  "key-adapter": {"layoutAlias": "K adapter", "shortName": "K Proj", "title": "Cross-attention K projection", "explanation": "用学习到的权重对缓存的 prefix K 做线性投影，供 action expert 的 Cross-attention 使用。"},
  "value-adapter": {"layoutAlias": "V adapter", "shortName": "V Proj", "title": "Cross-attention V projection", "explanation": "用学习到的权重对缓存的 prefix V 做线性投影，供 action expert 的 Cross-attention 使用。"},
  "rearrange-key-heads": {"layoutAlias": "K heads", "shortName": "K 多头"},
  "rearrange-value-heads": {"layoutAlias": "V heads", "shortName": "V 多头"},
  "rms-norm": {"layoutAlias": "RMSNorm", "shortName": "RMSNorm"},
  "condition-projection": {"layoutAlias": "condition → 3D", "shortName": "条件 → 3D", "title": "Condition projection"},
  "scale-slice": {"layoutAlias": "scale", "shortName": "scale", "title": "Select scale"},
  "shift-slice": {"layoutAlias": "shift", "shortName": "shift", "title": "Select shift"},
  "gate-slice": {"layoutAlias": "gate", "shortName": "Gate", "title": "Select Gate"},
  "scale-product": {"layoutAlias": "× scale", "shortName": "× scale", "title": "RMSNorm × scale"},
  "scale-offset": {"layoutAlias": "1 + scale", "shortName": "1 + scale", "title": "RMSNorm residual addition", "explanation": "加回原 RMSNorm 结果，得到 RMSNorm(X) × (1 + scale)。"},
  "shift-add": {"layoutAlias": "+ shift", "shortName": "+ shift", "title": "Add shift", "explanation": "shift 来自时间条件投影，沿 token 轴广播后逐元素相加。"},
  "residual-gate": {"layoutAlias": "× gate", "shortName": "× Gate", "title": "Residual Gate multiplication"},
  "residual-add": {"layoutAlias": "Add", "shortName": "相加", "title": "Gated residual addition"},
  "final-rms-norm": {"layoutAlias": "Final RMSNorm", "shortName": "末层 RMSNorm"},
  "final-condition-projection": {"layoutAlias": "condition → 2D", "shortName": "条件 → 2D", "title": "Condition projection"},
  "final-scale-slice": {"layoutAlias": "scale", "shortName": "scale", "title": "Select scale"},
  "final-shift-slice": {"layoutAlias": "shift", "shortName": "shift", "title": "Select shift"},
  "final-scale-product": {"layoutAlias": "× scale", "shortName": "× scale", "title": "RMSNorm × scale"},
  "final-scale-offset": {"layoutAlias": "1 + scale", "shortName": "1 + scale", "title": "RMSNorm residual addition", "explanation": "加回原 RMSNorm 结果，得到 RMSNorm(X) × (1 + scale)。"},
  "final-shift-add": {"layoutAlias": "+ shift", "shortName": "+ shift", "title": "Add shift", "explanation": "shift 来自时间条件投影，沿 token 轴广播后逐元素相加。"},
  "grid-rearrange": {"layoutAlias": "Patch-grid merge", "shortName": "patch 网格合并"},
  "connector-projection": {"layoutAlias": "Project", "shortName": "Proj", "title": "Vision connector projection"},
  "connector-scale": {"layoutAlias": "×√DOUT", "shortName": "×√DOUT"},
  "prompt-scale": {"layoutAlias": "×√D", "shortName": "×√D"},
  "pad-state": {"layoutAlias": "Zero-pad state", "shortName": "state 补零"},
  "pair-key-layers": {"layoutAlias": "K layer pairs", "shortName": "按层 K", "title": "K layer indexing"},
  "pair-value-layers": {"layoutAlias": "V layer pairs", "shortName": "按层 V", "title": "V layer indexing"},
  "public-action-slice": {"layoutAlias": "Public boundary", "shortName": "输出边界", "title": "Public action selection"},
};

export const OPERATOR_KIND_NAMES: Readonly<Record<string, string>> = {
  "linear": "Linear projection",
  "patch-embedding": "Patch embedding",
  "token-embedding": "Embedding lookup",
  "layer-norm": "LayerNorm",
  "rms-norm": "RMSNorm",
  "attention-core": "Attention",
  "rope": "RoPE",
  "gelu": "GELU",
  "silu": "SiLU",
  "slice": "Slice",
  "reshape": "Reshape",
  "concat": "Concat",
  "permute-rearrange": "Permute",
  "residual-add": "Elementwise addition",
  "elementwise-multiply": "Elementwise multiplication",
  "scalar-scale": "Scalar multiplication",
  "sinusoidal-time-embedding": "Sinusoidal time embedding",
  "euler-update": "Euler update"
};

export const operatorAliases: Readonly<Record<string, string>> = Object.fromEntries(
  Object.entries(OPERATOR_CATALOG).flatMap(([role, item]) => item.layoutAlias ? [[role, item.layoutAlias]] : []));
export const operatorShortNames: Readonly<Record<string, string>> = Object.fromEntries(
  Object.values(OPERATOR_CATALOG).flatMap(item => item.layoutAlias && item.shortName ? [[item.layoutAlias, item.shortName]] : []));

/** Sentence case for DAG names; one-letter tensor symbols and established acronyms keep their notation. */
export function dagLabel(text: string): string {
  return text.replace(/(^|[+×/]\s*)([a-z][a-z]+)/g, (_, prefix: string, word: string) => prefix + word[0]!.toUpperCase() + word.slice(1));
}
