/** Shared UI vocabulary. Source labels remain usable as aliases across models. */
export const SHARED_TERMINOLOGY: Readonly<Record<string, string>> = {
  "Prefix Encoder": "前缀编码器",
  "Prefix encoder": "前缀编码器",
  "VLM prefix encoder": "前缀编码器",
  "VLM": "前缀编码器",
  "Images": "图像",
  "Executed images": "图像",
  "512² execution": "图像",
  "Prompt": "prompt",
  "Prompt tokens": "prompt",
  "Prompt token IDs": "prompt",
  "Prompt + state tokens": "prompt + state",
  "State input": "state",
  "State scalars": "state",
  "State": "state",
  "State token": "state token",
  "Attn": "Attention",
  "attention": "Attention",
  "Self-attention core": "Self-attention",
  "Cross-attention core": "Cross-attention",
  "Gate": "gate",
  "gate": "gate",
  "bias": "bias",
  "scale": "scale",
  "shift": "shift",
  "× scale": "× scale",
  "1 + scale": "1 + scale",
  "+ shift": "+ shift",
  "× gate": "× gate",
  "Patch": "patch",
  "Token embed": "Embedding",
  "Token embedding": "token embedding",
  "embedding": "embedding",
  "reshape": "reshape",
  "concat": "concat",
  "tokens": "token",
  "token_ids": "token ID",
  "prompt_token_ids": "prompt token ID",
  "view_tokens": "视觉 token",
};

export const WORKLOAD_LABELS: Readonly<Record<string, string>> = {
  V: "相机视角",
  L_PROMPT: "prompt token 数",
  T_ACTION: "动作 token 数",
  N_DENOISE: "去噪步数",
};
