import { operatorShortNames } from "./operatorCatalog";

/** Shared source synonyms and UI prose. Operator names are owned by operatorCatalog. */
export const SHARED_TERMINOLOGY: Readonly<Record<string, string>> = {
  "Attention": "Attention",
  "MLP": "MLP",
  "Vision Encoder": "视觉编码器",
  "Action Flow Decoder": "动作解码器",
  "Noise x₀": "噪声 x₀",
  "Prefix out": "前缀输出",
  "Actions": "动作输出",
  "Denoise ×{count}": "去噪 ×{count}",
  "MLP Norm": "MLP 归一化",
  "Final Norm": "末层归一化",
  "Velocity proj": "速度 Proj",
  "Attention LayerNorm": "Attention LayerNorm",
  "Query projection": "Q 投影",
  "Key projection": "K 投影",
  "Value projection": "V 投影",
  "Attention output projection": "Attention 输出投影",
  "Attention residual": "Attention 残差相加",
  "MLP LayerNorm": "MLP LayerNorm",
  "MLP up projection": "MLP 升维投影",
  "MLP GELU": "MLP GELU",
  "MLP down projection": "MLP 降维投影",
  "MLP residual": "MLP 残差相加",
  "Attention RMSNorm": "Attention RMSNorm",
  "MQA query projection": "MQA Q 投影",
  "MQA key projection": "MQA K 投影",
  "MQA value projection": "MQA V 投影",
  "Query RoPE": "Q RoPE",
  "Key RoPE": "K RoPE",
  "Prefix attention core": "前缀 Attention 计算",
  "Stack attention key and value": "堆叠 Attention K/V",
  "Read matched-layer prefix keys": "读取对应层的前缀 K",
  "Read matched-layer prefix values": "读取对应层的前缀 V",
  "Action query projection": "动作 Q 投影",
  "Action key projection": "动作 K 投影",
  "Action value projection": "动作 V 投影",
  "Action query RoPE": "动作 Q RoPE",
  "Action key RoPE": "动作 K RoPE",
  "Logical view of prefix and current-suffix keys": "前缀与当前后缀 K 的逻辑视图",
  "Logical view of prefix and current-suffix values": "前缀与当前后缀 V 的逻辑视图",
  "Action attention core": "动作 Attention 计算",
  "MLP RMSNorm": "MLP RMSNorm",
  "Gate projection": "Gate 投影",
  "Up projection": "升维投影",
  "Gate GELU": "Gate GELU",
  "Gated MLP product": "Gate MLP 逐元素乘积",
  "Down projection": "降维投影",
  "Patch projection": "patch 投影",
  "Vision output LayerNorm": "视觉输出 LayerNorm",
  "Multimodal projection": "多模态投影",
  "Flatten view tokens": "展平视角 token",
  "Prompt token embedding": "prompt embedding",
  "Concatenate view and prompt tokens": "拼接视觉与 prompt token",
  "State projection": "state 投影",
  "Noisy-action projection": "带噪动作投影",
  "Sinusoidal timestep embedding": "正弦时间步 embedding",
  "Concatenate action and time": "拼接动作与时间",
  "Action-time MLP input projection": "动作时间 MLP 输入投影",
  "Action-time SiLU": "动作时间 SiLU",
  "Action-time MLP output projection": "动作时间 MLP 输出投影",
  "Concatenate state and action tokens": "拼接状态与动作 token",
  "Select final action-token rows": "选择末尾动作 token 行",
  "Velocity projection": "速度投影",
  "Euler update": "欧拉更新",
  "Patch embedding": "patch embedding",
  "Linear projection": "线性投影",
  "Layer normalization": "层归一化",
  "RMS normalization": "RMS 归一化",
  "Rotary position embedding": "旋转位置 embedding",
  "Attention core": "Attention 计算",
  "GELU activation": "GELU 激活",
  "SiLU activation": "SiLU 激活",
  "Elementwise multiply": "逐元素相乘",
  "Residual addition": "残差相加",
  "Concatenation": "concat",
  "Reshape or logical row selection": "形状重排或逻辑行选择",
  "Logical slice": "slice",
  "Sinusoidal time embedding": "正弦时间 embedding",
  "Euler flow update": "欧拉流更新",
  "Latent robot state": "机器人潜在状态",
  "Initial noise/action state": "初始噪声与动作状态",
  "Loop-carried action state": "循环携带的动作状态",
  "Final prefix stack hidden state": "前缀堆叠的最终隐状态",
  "Final action state": "最终动作状态",
  "Inspect {description}": "查看算子：{description}",
  "linear": "线性运算",
  "normalization": "归一化",
  "position": "位置编码",
  "activation": "激活",
  "elementwise": "逐元素运算",
  "shape": "形状变换",
  "input": "输入",
  "output": "输出",
  "residual": "残差",
  "query": "Q",
  "key": "K",
  "value": "V",
  "update": "更新量",
  "hidden": "隐状态",
  "prefix_kv": "前缀 K/V",
  "right": "右输入",
  "left": "左输入",
  "suffix": "后缀",
  "images": "图像",
  "image": "图像",
  "prefix": "前缀",
  "state": "state",
  "action_state": "动作状态",
  "timestep": "时间步",
  "expert_hidden": "专家隐状态",
  "updated_action_state": "新动作状态",
  "velocity": "速度",
  "updated_state": "新状态",
  "initial": "初始状态",
  "iteration_input": "迭代输入",
  "iteration_output": "迭代输出",
  "final": "最终状态",
  "flops": "FLOPs",
  "read_elements": "读取元素",
  "write_elements": "写入元素",
  "elements": "元素",
  "unresolved": "未解析",
  "Multiply and add count as two FLOPs; logical operand elements are counted once; bias, activation, cache behavior, runtime dtype, packing, quantization metadata, and fusion are excluded.": "乘法与加法分别计为一次 FLOP；逻辑操作数元素仅计一次。不包含 bias、激活、缓存行为、运行时数据类型、打包、量化元数据与融合。",
  "Vision encoder": "视觉编码器",
  "Action flow decoder": "动作解码器",
  "Public action contract": "动作输出",
  "图块合并": "patch 合并",
  "图文拼接": "concat",
  "动作拼接": "动作 + 时间",
  "SigLIP blocks": "SigLIP 块",
  "Vision transformer blocks": "视觉 Transformer 块",
  "Full Gemma prefix blocks": "完整 Gemma 前缀块",
  "Full Gemma": "完整 Gemma 块",
  "AdaRMS expert layers": "AdaRMS 专家层",
  "Executed SmolVLM blocks": "SmolVLM 块",
  "Ordered self/cross expert pairs": "Self-attention → Cross-attention",
  "Prefix attention": "前缀 Attention",
  "Output projection": "输出投影",
  "Cache key": "缓存 K",
  "Cache value": "缓存 V",
  "Gated product": "Gate 乘积",
  "Sinusoidal time": "正弦时间 embedding",
  "Action projection": "动作投影",
  "Read prefix key": "读取前缀 K",
  "Read prefix value": "读取前缀 V",
  "Prefix + suffix key": "前缀 + 后缀 K",
  "Prefix + suffix value": "前缀 + 后缀 V",
  "Attention output": "Attention 输出",
  "Scale slice": "选择 scale",
  "Shift slice": "选择 shift",
  "Gate slice": "选择 Gate",
  "RMS times scale": "RMS × scale",
  "Apply one plus scale": "加入基础分量",
  "Apply shift": "加入 shift",
  "Gate branch": "分支 Gate",
  "Gated residual": "Gate 残差相加",
  "Scale / shift / gate": "scale / shift / Gate",
  "Final scale / shift / gate": "末层 scale / shift / Gate",
  "Time MLP in": "时间 MLP 输入",
  "Time MLP out": "时间 MLP 输出",
  "Expert query": "专家 Q",
  "Expert key": "专家 K",
  "Expert value": "专家 V",
  "Bidirectional suffix attention": "后缀双向 Attention",
  "Causal suffix self-attention": "后缀因果 Self-attention",
  "Prefix-only cross-attention": "前缀 Cross-attention",
  "Self-attention residual": "Self-attention 残差相加",
  "Cross-attention residual": "Cross-attention 残差相加",
  "Select even-layer key": "选择偶数层 K",
  "Select even-layer value": "选择偶数层 V",
  "Select odd-layer key": "选择奇数层 K",
  "Select odd-layer value": "选择奇数层 V",
  "Flatten cached key heads": "展平缓存 K 多头",
  "Flatten cached value heads": "展平缓存 V 多头",
  "Cross key adapter": "Cross-attention K projection",
  "Cross value adapter": "Cross-attention V projection",
  "Restore key heads": "恢复 K 多头",
  "Restore value heads": "恢复 V 多头",
  "Connector projection": "连接器投影",
  "Scale connector by √DOUT": "连接器 ×√DOUT",
  "Scale language by √D": "文本 ×√D",
  "Language embedding": "prompt embedding",
  "Image + language": "图像 + 语言",
  "Append state token": "拼接 state token",
  "Pair even / odd keys": "按层索引 K（偶数 / 奇数层）",
  "Pair even / odd values": "按层索引 V（偶数 / 奇数层）",
  "Broadcast time": "广播时间",
  "Action + time": "动作 + 时间",
  "Fusion projection": "融合投影",
  "Fusion output": "融合输出",
  "Expose public action dimensions": "选择输出动作维度",
  "Permute / rearrange": "维度置换 / 重排",
  "Scale by a declared scalar": "标量 scale",
  "Attention AdaRMS": "Attention AdaRMS",
  "Cached self-attention": "缓存 Self-attention",
  "Attention gated residual": "Attention Gate 残差",
  "MLP AdaRMS": "MLP AdaRMS",
  "Gated GELU MLP": "Gate GELU MLP",
  "MLP gated residual": "MLP Gate 残差",
  "Even layer: cached self-attention": "偶数层：缓存 Self-attention",
  "Even layer: gated SiLU MLP": "偶数层：Gate SiLU MLP",
  "Odd layer: prefix cross-attention": "奇数层：前缀 Cross-attention",
  "Odd layer: gated SiLU MLP": "奇数层：Gate SiLU MLP",
  "Prefix Encoder": "前缀编码器",
  "Prefix encoder": "前缀编码器",
  "VLM prefix encoder": "前缀编码器",
  "VLM": "前缀编码器",
  "Images": "图像",
  "Executed images": "图像",
  "512² execution": "图像",
  "Prompt": "prompt",
  "Prompt tokens": "prompt",
  "Prompt token IDs": "prompt",
  "Prompt + state tokens": "prompt + state",
  "State input": "state",
  "State scalars": "state",
  "State": "state",
  "条件投影": "条件 Proj",
  "输入投影": "输入 Proj",
  "输出投影": "输出 Proj",
  "attention": "Attention",
  "Self-attention core": "Self-attention",
  "Cross-attention core": "Cross-attention",
  "bias": "bias",
  "Token embedding": "token embedding",
  "embedding": "embedding",
  "tokens": "token",
  "token_ids": "token ID",
  "prompt_token_ids": "prompt token ID",
  "view_tokens": "视觉 token",
  ...operatorShortNames,
};

export const WORKLOAD_LABELS: Readonly<Record<string, string>> = {
  V: "相机视角",
  L_PROMPT: "prompt token 数",
  T_ACTION: "动作 token 数",
  N_DENOISE: "去噪步数",
};
